dist: trusty
language: elixir
matrix:
  include:
    - elixir:  1.8
      otp_release: 22.1
    - elixir:  1.7
      otp_release: 22.1
services:
  - rabbitmq
script:
  - mix credo --strict
  - mix test