version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.9.9-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  healthy:
    image: alpine
    command: echo "All services started and healthy!"
    depends_on:
      rabbitmq:
        condition: service_healthy
