name: CI
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}

    env:
      MIX_ENV: test

    strategy:
      matrix:
        otp: ['23', '24', '25']
        elixir: ['1.11', '1.12', '1.13', '1.14']
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{matrix.elixir}}
      - name: Restore the deps cache
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-deps-mixlockhash-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-deps-
      - name: Restore the _build cache
        uses: actions/cache@v1
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ env.MIX_ENV }}-build-mixlockhash-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ env.MIX_ENV }}-build-
      - run: mix deps.get
      - run: mix test